永豐:
  https://bank.sinopac.com/mma8/bank/html/rate/bank_ExchangeRate.html
永豐銀行:
  https://bank.sinopac.com/mma8/bank/html/rate/bank_ExchangeRate.html
台銀:
  http://rate.bot.com.tw/xrt?Lang=zh-TW
台灣銀行:
  http://rate.bot.com.tw/xrt?Lang=zh-TW
兆豐:
  https://www.megabank.com.tw/other/bulletin02_02.asp
兆豐商銀:
  https://www.megabank.com.tw/other/bulletin02_02.asp
兆豐銀行:
  https://www.megabank.com.tw/other/bulletin02_02.asp
華南:
  https://netbank.hncb.com.tw/netbank/pages/jsp/ExtSel/RTExange.html
華南銀行:
  https://netbank.hncb.com.tw/netbank/pages/jsp/ExtSel/RTExange.html
合庫:
  https://www.tcb-bank.com.tw/finance_info/Pages/foreign_spot_rate.aspx
合作金庫:
  https://www.tcb-bank.com.tw/finance_info/Pages/foreign_spot_rate.aspx
玉山:
  https://www.esunbank.com.tw/bank/personal/deposit/rate/forex/foreign-exchange-rates
玉山銀行:
  https://www.esunbank.com.tw/bank/personal/deposit/rate/forex/foreign-exchange-rates
土地銀行:
  https://ebank.landbank.com.tw/infor/infor.aspx?__eventtarget=querycurrency
土銀:
  https://ebank.landbank.com.tw/infor/infor.aspx?__eventtarget=querycurrency
彰銀:
  https://www.bankchb.com/frontend/G0100.html
彰化銀行:
  https://www.bankchb.com/frontend/G0100.html
中華郵政:
  https://ipost.post.gov.tw/webpost/CSController?cmd=POS1002_1&_SYS_ID=B&_MENU_ID=179&_ACTIVE_ID=183
郵局:
  https://ipost.post.gov.tw/webpost/CSController?cmd=POS1002_1&_SYS_ID=B&_MENU_ID=179&_ACTIVE_ID=183
陽信:
  https://www.esunnybank.com.tw/sunnyNBWeb/NB0912/NB091205/NB091205Index.seam?menu=NB091205
陽信銀行:
  https://www.esunnybank.com.tw/sunnyNBWeb/NB0912/NB091205/NB091205Index.seam?menu=NB091205
星展:
  http://www.dbs.com.tw/personal-zh/rates/foreign-exchange-rates.page
星展銀行:
  http://www.dbs.com.tw/personal-zh/rates/foreign-exchange-rates.page
大眾:
  http://www.tcbank.com.tw/tw/ExchangeRate/Current
大眾銀行:
  http://www.tcbank.com.tw/tw/ExchangeRate/Current
凱基:
  https://www.kgibank.com/T01/T0111/rate03.jsp
凱基銀行:
  https://www.kgibank.com/T01/T0111/rate03.jsp
中信:
  https://www.ctbcbank.com/CTCBPortalWeb/toPage?id=TW_RB_CM_ebank_018001
中信銀行:
  https://www.ctbcbank.com/CTCBPortalWeb/toPage?id=TW_RB_CM_ebank_018001
中國信託:
  https://www.ctbcbank.com/CTCBPortalWeb/toPage?id=TW_RB_CM_ebank_018001
元大:
  https://www.yuantabank.com.tw/bank/currency/program/currency_01.aspx
元大銀行:
  https://www.yuantabank.com.tw/bank/currency/program/currency_01.aspx
遠銀:
  https://www.feib.com.tw/financialinfo/exchangerate03.aspx
遠東商銀:
  https://www.feib.com.tw/financialinfo/exchangerate03.aspx
遠東銀行:
  https://www.feib.com.tw/financialinfo/exchangerate03.aspx
花旗:
  https://www.citibank.com.tw/TWGCB/apba/fxrts/InitializeSubApp.do?TTC=29&selectedBCC=TWD
花旗台灣:
  https://www.citibank.com.tw/TWGCB/apba/fxrts/InitializeSubApp.do?TTC=29&selectedBCC=TWD
花旗銀行:
  https://www.citibank.com.tw/TWGCB/apba/fxrts/InitializeSubApp.do?TTC=29&selectedBCC=TWD
上海:
  https://ibank.scsb.com.tw/netbank.portal?_nfpb=true&_pageLabel=page_other12&_nfls=false
上海商銀:
  https://ibank.scsb.com.tw/netbank.portal?_nfpb=true&_pageLabel=page_other12&_nfls=false
上海銀行:
  https://ibank.scsb.com.tw/netbank.portal?_nfpb=true&_pageLabel=page_other12&_nfls=false
台新:
  https://www.taishinbank.com.tw/TS/TS06/TS0605/TS060502/index.htm?urlPath1=TS02&urlPath2=TS0202
台新銀行:
  https://www.taishinbank.com.tw/TS/TS06/TS0605/TS060502/index.htm?urlPath1=TS02&urlPath2=TS0202
日盛:
  https://netbank.jihsunbank.com.tw/Rate/ExgRate.htm
日盛銀行:
  https://netbank.jihsunbank.com.tw/Rate/ExgRate.htm
富邦:
  https://www.fubon.com/banking/personal/deposit/Foreign_Exchange/Foreign_Exchange.htm
台北富邦:
  https://www.fubon.com/banking/personal/deposit/Foreign_Exchange/Foreign_Exchange.htm
富邦銀行:
  https://www.fubon.com/banking/personal/deposit/Foreign_Exchange/Foreign_Exchange.htm
一銀:
  https://www.firstbank.com.tw/A5.1.2.1.html
第一銀行:
  https://www.firstbank.com.tw/A5.1.2.1.html
三信:
  https://www.cotabank.com.tw/web/interest_3
三信商銀:
  https://www.cotabank.com.tw/web/interest_3
三信銀行:
  https://www.cotabank.com.tw/web/interest_3
渣打:
  http://www.standardchartered.com.tw/check/inquiry-rate-foreign-exchange.asp
渣打銀行:
  http://www.standardchartered.com.tw/check/inquiry-rate-foreign-exchange.asp
安泰:
  http://www.entiebank.com.tw/rate/hostRate_M.asp
安泰商銀:
  http://www.entiebank.com.tw/rate/hostRate_M.asp
匯豐:
  https://www.hsbc.com.tw/1/2/Misc/popup-tw/currency-calculator
匯豐台灣:
  https://www.hsbc.com.tw/1/2/Misc/popup-tw/currency-calculator
匯豐銀行:
  https://www.hsbc.com.tw/1/2/Misc/popup-tw/currency-calculator