阿拉伯聯合大公國迪拉姆: 
  AED 
阿根廷披索: 
  ARS 
澳幣: 
  AUD 
保加利亞列弗: 
  BGN 
汶萊元: 
  BND 
玻利維亞幣: 
  BOB 
巴西雷亞爾: 
  BRL 
加幣: 
  CAD 
瑞士法郎: 
  CHF 
智利披索: 
  CLP 
中國人民幣: 
  CNY 
人民幣: 
  CNY 
哥倫比亞披索: 
  COP 
捷克克郎: 
  CZK 
丹麥克朗: 
  DKK 
埃及鎊: 
  EGP 
歐元: 
  EUR 
歐圓: 
  EUR 
斐濟元: 
  FJD 
英鎊: 
  GBP 
港幣: 
  HKD 
克羅埃西亞克朗: 
  HRK 
匈牙利福林: 
  HUF 
印尼盧比: 
  IDR 
以色列新舍克: 
  ILS 
印度盧比: 
  INR 
日圓: 
  JPY 
日元: 
  JPY 
日幣: 
  JPY 
肯亞先令: 
  KES 
韓元: 
  KRW 
立陶宛利塔斯: 
  LTL 
摩洛哥迪拉姆: 
  MAD 
墨西哥披索: 
  MXN 
馬來西亞林吉特: 
  MYR 
挪威克朗: 
  NOK 
紐西蘭幣: 
  NZD 
祕魯幣: 
  PEN 
菲律賓披索: 
  PHP 
巴基斯坦盧比: 
  PKR 
波蘭茲羅提: 
  PLN 
羅馬尼亞列伊: 
  RON 
塞爾維亞第納爾: 
  RSD 
俄羅斯盧布: 
  RUB 
沙烏地阿拉伯里亞爾: 
  SAR 
瑞典克朗: 
  SEK 
新加坡幣: 
  SGD 
新幣: 
  SGD 
泰銖: 
  THB 
土耳其里拉: 
  TRY 
新臺幣: 
  TWD 
烏克蘭赫里納: 
  UAH 
美元: 
  USD 
委內瑞拉銀幣: 
  VEF 
越南盾: 
  VND 
南非蘭特: 
  ZAR 